#!/usr/bin/env bash
# Builds the C libraries (FreeType, stb_image, a small compiler-rt subset and the few
# wasi-libc routines they use) as wasm32 object files for Free Pascal's internal
# WebAssembly linker (MVP feature set, no exception handling, no reference types).
#
# Needs: LLVM clang with the wasm32 target (brew install llvm) and wasi-libc
# (brew install wasi-libc). Override with LLVM=... WASI_SYSROOT=...
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LLVM="${LLVM:-/opt/homebrew/opt/llvm/bin}"
SYSROOT="${WASI_SYSROOT:-/opt/homebrew/opt/wasi-libc/share/wasi-sysroot}"
# FreeType 2.6.1 is the version the Windows client of Soldat 1.7.1 ships (freetype.dll);
# later versions hint and size the Play font differently (other glyph shapes and widths,
# 1 px taller x-height at some sizes, other ascender rounding)
FT="$HERE/freetype-VER-2-6-1"
OUT="$HERE/obj"

if [ ! -d "$FT" ]; then
  echo "Fetching FreeType 2.6.1..."
  curl -fsSL -o "$HERE/ft.tar.gz" \
    "https://gitlab.freedesktop.org/freetype/freetype/-/archive/VER-2-6-1/freetype-VER-2-6-1.tar.gz"
  tar -xzf "$HERE/ft.tar.gz" -C "$HERE"
  # the renderer's overflow handling uses setjmp/longjmp, which this toolchain lacks, and
  # the auto-hinter calls its hinting functions through a pointer of another type (an
  # indirect call with a mismatched signature traps in WebAssembly)
  patch -d "$FT" -p1 < "$HERE/freetype-wasm.patch"
fi

mkdir -p "$OUT"

CFLAGS=(--target=wasm32-wasip1 --sysroot="$SYSROOT" -O2
        -mcpu=mvp -msign-ext -mbulk-memory -mnontrapping-fptoint -mmutable-globals
        -fno-stack-protector -DNDEBUG)

FT_SRCS=(base/ftinit base/ftdebug base/ftbase base/ftbitmap base/ftglyph
         base/ftbbox base/ftmm truetype/truetype sfnt/sfnt smooth/smooth raster/raster
         autofit/autofit psnames/psnames gzip/ftgzip)

for f in "${FT_SRCS[@]}"; do
  "$LLVM/clang" "${CFLAGS[@]}" -I"$HERE/shim" \
    -DFT2_BUILD_LIBRARY '-DFT_CONFIG_MODULES_H=<freetype/config/ftmodule.h>' \
    -I"$HERE/ftcfg" -I"$FT/include" -c "$FT/src/$f.c" -o "$OUT/ft_$(basename "$f").o"
done

"$LLVM/clang" "${CFLAGS[@]}" -I"$HERE/shim" -DFT2_BUILD_LIBRARY \
  '-DFT_CONFIG_MODULES_H=<freetype/config/ftmodule.h>' -I"$HERE/ftcfg" -I"$FT/include" \
  -c "$HERE/ftsystem_mem.c" -o "$OUT/ft_ftsystem_mem.o"
# named differently from the Pascal unit "stb" (whose object is stb.o)
"$LLVM/clang" "${CFLAGS[@]}" -DSTBI_NO_STDIO -c "$HERE/stb/stb_wasm.c" -o "$OUT/stbimage_c.o"
"$LLVM/clang" "${CFLAGS[@]}" -c "$HERE/rtbuiltins.c" -o "$OUT/rtbuiltins.o"

# the internal linker takes object files only: pull the needed libc members out
mkdir -p "$OUT/libc"
LLVM="$LLVM" WASI_SYSROOT="$SYSROOT" python3 "$HERE/extract-libc.py" "$OUT" "$OUT/libc"
echo "C objects built in $OUT"

# object list for src/web/CLibs.pas
{
  echo "{ generated by c/build-c.sh }"
  for f in "$OUT"/*.o "$OUT"/libc/*.o; do echo "{\$L $(basename "$f")}"; done
} > "$HERE/../src/web/clibs.inc"
