{
  Links the C libraries compiled for wasm32 (see c/build-c.sh) into the module:
  FreeType, stb_image and the few libc/compiler-rt routines they need.
  The objects are found through the -Fo search path; clibs.inc lists them and is
  generated by c/build-c.sh.
}
unit CLibs;

{$mode delphi}

interface

uses
  CHeap;

implementation

{$I clibs.inc}

end.
