{
  OpenGL binding for the WebAssembly build of Soldat (replaces dglOpenGL).

  The GL entry points are procedure variables (like dglOpenGL) that InitOpenGL points at
  functions imported from JavaScript (module "gl"), which implements them on WebGL2.
  Generated from the dglOpenGL declarations of the functions the renderer uses.
}
unit dglOpenGL;

{$mode delphi}

interface

type
  GLenum = Cardinal;
  GLboolean = ByteBool;
  GLbitfield = Cardinal;
  GLbyte = ShortInt;
  GLshort = SmallInt;
  GLint = Integer;
  GLsizei = Integer;
  GLubyte = Byte;
  GLushort = Word;
  GLuint = Cardinal;
  GLfloat = Single;
  GLclampf = Single;
  GLdouble = Double;
  GLclampd = Double;
  GLvoid = Pointer;
  GLhandle = Cardinal;
  GLchar = AnsiChar;
  GLintptr = GLint;
  GLsizeiptr = GLsizei;
  PGLvoid = Pointer;
  PGLboolean = ^GLboolean;
  PGLubyte = ^GLubyte;
  PGLint = ^GLint;
  PGLuint = ^GLuint;
  PGLsizei = ^GLsizei;
  PGLfloat = ^GLfloat;
  PGLchar = PAnsiChar;
  PPGLchar = ^PGLchar;

const
  GL_FALSE = 0;
  GL_TRUE = 1;
  GL_ALPHA = $1906;
  GL_ARRAY_BUFFER = $8892;
  GL_BLEND = $0BE2;
  GL_CLAMP_TO_EDGE = $812F;
  GL_COLOR_ARRAY = $8076;
  GL_COLOR_ATTACHMENT0 = $8CE0;
  GL_COLOR_BUFFER_BIT = $00004000;
  GL_COMPILE_STATUS = $8B81;
  GL_DEPTH_TEST = $0B71;
  GL_DITHER = $0BD0;
  GL_DRAW_FRAMEBUFFER = $8CA9;
  GL_ELEMENT_ARRAY_BUFFER = $8893;
  GL_FLOAT = $1406;
  GL_FRAGMENT_SHADER = $8B30;
  GL_FRAMEBUFFER = $8D40;
  GL_GENERATE_MIPMAP = $8191;
  GL_GENERATE_MIPMAP_HINT = $8192;
  GL_INFO_LOG_LENGTH = $8B84;
  GL_LINEAR = $2601;
  GL_LINEAR_MIPMAP_LINEAR = $2703;
  GL_LINK_STATUS = $8B82;
  GL_LUMINANCE_ALPHA = $190A;
  GL_MAX_TEXTURE_SIZE = $0D33;
  GL_MULTISAMPLE = $809D;
  GL_NEAREST = $2600;
  GL_NEAREST_MIPMAP_NEAREST = $2700;
  GL_NICEST = $1102;
  GL_ONE = 1;
  GL_ONE_MINUS_SRC_ALPHA = $0303;
  GL_PACK_ALIGNMENT = $0D05;
  GL_READ_FRAMEBUFFER = $8CA8;
  GL_REPEAT = $2901;
  GL_RGB = $1907;
  GL_RGBA = $1908;
  GL_SAMPLES = $80A9;
  GL_STATIC_DRAW = $88E4;
  GL_STREAM_DRAW = $88E0;
  GL_TEXTURE0 = $84C0;
  GL_TEXTURE1 = $84C1;
  GL_TEXTURE_2D = $0DE1;
  GL_TEXTURE_2D_MULTISAMPLE = $9100;
  GL_TEXTURE_COORD_ARRAY = $8078;
  GL_TEXTURE_FILTER_CONTROL = $8500;
  GL_TEXTURE_LOD_BIAS = $8501;
  GL_TEXTURE_MAG_FILTER = $2800;
  GL_TEXTURE_MIN_FILTER = $2801;
  GL_TEXTURE_WRAP_S = $2802;
  GL_TEXTURE_WRAP_T = $2803;
  GL_TRIANGLES = $0004;
  GL_UNPACK_ALIGNMENT = $0CF5;
  GL_UNSIGNED_BYTE = $1401;
  GL_UNSIGNED_SHORT = $1403;
  GL_VERSION = $1F02;
  GL_VERTEX_ARRAY = $8074;
  GL_VERTEX_SHADER = $8B31;
  GL_RENDERER = $1F01;
  GL_VENDOR = $1F00;
  GL_NO_ERROR = 0;
  GL_LUMINANCE = $1909;
  GL_ONE_MINUS_DST_ALPHA = $0305;
  GL_SRC_ALPHA = $0302;
  GL_DST_ALPHA = $0304;
  GL_ZERO = 0;
  GL_TEXTURE_BINDING_2D = $8069;
  GL_FRAMEBUFFER_BINDING = $8CA6;
  GL_RGBA8 = $8058;
  GL_BGRA = $80E1;
  GL_DYNAMIC_DRAW = $88E8;
  GL_SCISSOR_TEST = $0C11;
  GL_CULL_FACE = $0B44;
  GL_STENCIL_TEST = $0B90;
  GL_STENCIL_BUFFER_BIT = $00000400;
  GL_STENCIL_BITS = $0D57;
  GL_ALWAYS = $0207;
  GL_EQUAL = $0202;
  GL_KEEP = $1E00;
  GL_REPLACE = $1E01;

type
  TglActiveTexture = procedure(texture: GLenum); cdecl;
  TglAttachShader = procedure(programObj, shaderObj: GLhandle); cdecl;
  TglBindAttribLocation = procedure(programObj: GLhandle; index: GLuint; name: PGLChar); cdecl;
  TglBindBuffer = procedure(target: GLenum; buffer: GLuint); cdecl;
  TglBindFramebuffer = procedure(target: GLenum; framebuffer: GLuint); cdecl;
  TglBindTexture = procedure(target: GLenum; texture: GLuint); cdecl;
  TglBlendFunc = procedure(sfactor: GLenum; dfactor: GLenum); cdecl;
  TglBlitFramebuffer = procedure(srcX0: GLint; srcY0: GLint; srcX1: GLint; srcY1: GLint; dstX0: GLint; dstY0: GLint; dstX1: GLint; dstY1: GLint; mask: GLbitfield; filter: GLenum); cdecl;
  TglBufferData = procedure(target: GLenum; size: GLsizeiptr; const data: PGLvoid; usage: GLenum); cdecl;
  TglBufferSubData = procedure(target: GLenum; offset: GLintptr; size: GLsizeiptr; const data: PGLvoid); cdecl;
  TglClear = procedure(mask: GLbitfield); cdecl;
  TglClearColor = procedure(red: GLclampf; green: GLclampf; blue: GLclampf; alpha: GLclampf); cdecl;
  TglColorPointer = procedure(size: GLint; _type: GLenum; stride: GLsizei; const _pointer: PGLvoid); cdecl;
  TglCompileShader = procedure(shaderObj: GLhandle); cdecl;
  TglCreateProgram = function: GLhandle; cdecl;
  TglCreateShader = function(shaderType: GLenum): GLhandle; cdecl;
  TglDeleteBuffers = procedure(n: GLsizei; const buffers: PGLuint); cdecl;
  TglDeleteFramebuffers = procedure(n: GLsizei; const framebuffers: PGLuint); cdecl;
  TglDeleteProgram = procedure(programObj: GLhandle); cdecl;
  TglDeleteShader = procedure(shaderObj: GLhandle); cdecl;
  TglDeleteTextures = procedure(n: GLsizei; const textures: PGLuint); cdecl;
  TglDetachShader = procedure(programObj, shaderObj: GLhandle); cdecl;
  TglDisable = procedure(cap: GLenum); cdecl;
  TglDrawArrays = procedure(mode: GLenum; first: GLint; count: GLsizei); cdecl;
  TglDrawElements = procedure(mode: GLenum; count: GLsizei; _type: GLenum; const indices: PGLvoid); cdecl;
  TglEnable = procedure(cap: GLenum); cdecl;
  TglEnableClientState = procedure(_array: GLenum); cdecl;
  TglEnableVertexAttribArray = procedure(index: GLuint); cdecl;
  TglFinish = procedure(); cdecl;
  TglFramebufferTexture2D = procedure(target: GLenum; attachment: GLenum; textarget: GLenum; texture: GLuint; level: GLint); cdecl;
  TglGenBuffers = procedure(n: GLsizei; buffers: PGLuint); cdecl;
  TglGenFramebuffers = procedure(n: GLsizei; framebuffers: PGLuint); cdecl;
  TglGenTextures = procedure(n: GLsizei; textures: PGLuint); cdecl;
  TglGenerateMipmap = procedure(target: GLenum); cdecl;
  TglGetIntegerv = procedure(pname: GLenum; params: PGLint); cdecl;
  TglGetProgramInfoLog = procedure(programObj: GLHandle; maxLength: glsizei; length: PGLSizei; infoLog: PGLChar); cdecl;
  TglGetProgramiv = procedure(programObj: GLhandle; pname: GLenum; params: PGLInt); cdecl;
  TglGetShaderInfoLog = procedure(shaderObj: GLHandle; maxLength: glsizei; length: PGLSizei; infoLog: PGLChar); cdecl;
  TglGetShaderiv = procedure(shaderObj: GLhandle; pname: GLenum; params: PGLInt); cdecl;
  TglGetString = function(name: GLenum): PAnsiChar; cdecl;
  TglGetUniformLocation = function(programObj: GLhandle; const char: PGLChar): glint; cdecl;
  TglHint = procedure(target: GLenum; mode: GLenum); cdecl;
  TglLinkProgram = procedure(programObj: GLHandle); cdecl;
  TglLoadMatrixf = procedure(const m: PGLfloat); cdecl;
  TglPixelStorei = procedure(pname: GLenum; param: GLint); cdecl;
  TglReadPixels = procedure(x: GLint; y: GLint; width: GLsizei; height: GLsizei; format: GLenum; _type: GLenum; pixels: PGLvoid); cdecl;
  TglShaderSource = procedure(shaderObj: GLHandle; count: glsizei; const _string: PPGLChar; lengths: pglint); cdecl;
  TglTexCoordPointer = procedure(size: GLint; _type: GLenum; stride: GLsizei; const _pointer: PGLvoid); cdecl;
  TglTexEnvf = procedure(target: GLenum; pname: GLenum; param: GLfloat); cdecl;
  TglTexImage2D = procedure(target: GLenum; level: GLint; internalformat: GLint; width: GLsizei; height: GLsizei; border: GLint; format: GLenum; _type: GLenum; const pixels: PGLvoid); cdecl;
  TglTexImage2DMultisample = procedure(target: GLenum; samples: GLsizei; internalformat: GLint; width: GLsizei; height: GLsizei; fixedsamplelocations: GLboolean); cdecl;
  TglTexParameteri = procedure(target: GLenum; pname: GLenum; param: GLint); cdecl;
  TglTexSubImage2D = procedure(target: GLenum; level: GLint; xoffset: GLint; yoffset: GLint; width: GLsizei; height: GLsizei; format: GLenum; _type: GLenum; const pixels: PGLvoid); cdecl;
  TglUniform1i = procedure(location: GLint; v0: GLint); cdecl;
  TglUniform1f = procedure(location: GLint; v0: GLfloat); cdecl;
  TglUniform4f = procedure(location: GLint; v0, v1, v2, v3: GLfloat); cdecl;
  TglClearStencil = procedure(s: GLint); cdecl;
  TglStencilFunc = procedure(func: GLenum; ref: GLint; mask: GLuint); cdecl;
  TglStencilOp = procedure(fail, zfail, zpass: GLenum); cdecl;
  TglStencilMask = procedure(mask: GLuint); cdecl;
  TglUniformMatrix3fv = procedure(location: GLint; count: GLsizei; transpose: GLboolean; value: PGLfloat); cdecl;
  TglUseProgram = procedure(programObj: GLhandle); cdecl;
  TglVertexAttribPointer = procedure(index: GLuint; size: GLint; _type: GLenum; normalized: GLboolean; stride: GLsizei; const _pointer: PGLvoid); cdecl;
  TglVertexPointer = procedure(size: GLint; _type: GLenum; stride: GLsizei; const _pointer: PGLvoid); cdecl;
  TglViewport = procedure(x: GLint; y: GLint; width: GLsizei; height: GLsizei); cdecl;
  TglBindFramebufferEXT = procedure(target: GLenum; framebuffer: GLuint); cdecl;
  TglDeleteFramebuffersEXT = procedure(n: GLsizei; const framebuffers: PGLuint); cdecl;
  TglFramebufferTexture2DEXT = procedure(target: GLenum; attachment: GLenum; textarget: GLenum; texture: GLuint; level: GLint); cdecl;
  TglGenFramebuffersEXT = procedure(n: GLsizei; framebuffers: PGLuint); cdecl;
  TglGenerateMipmapEXT = procedure(target: GLenum); cdecl;

var
  glActiveTexture: TglActiveTexture;
  glAttachShader: TglAttachShader;
  glBindAttribLocation: TglBindAttribLocation;
  glBindBuffer: TglBindBuffer;
  glBindFramebuffer: TglBindFramebuffer;
  glBindTexture: TglBindTexture;
  glBlendFunc: TglBlendFunc;
  glBlitFramebuffer: TglBlitFramebuffer;
  glBufferData: TglBufferData;
  glBufferSubData: TglBufferSubData;
  glClear: TglClear;
  glClearColor: TglClearColor;
  glColorPointer: TglColorPointer;
  glCompileShader: TglCompileShader;
  glCreateProgram: TglCreateProgram;
  glCreateShader: TglCreateShader;
  glDeleteBuffers: TglDeleteBuffers;
  glDeleteFramebuffers: TglDeleteFramebuffers;
  glDeleteProgram: TglDeleteProgram;
  glDeleteShader: TglDeleteShader;
  glDeleteTextures: TglDeleteTextures;
  glDetachShader: TglDetachShader;
  glDisable: TglDisable;
  glDrawArrays: TglDrawArrays;
  glDrawElements: TglDrawElements;
  glEnable: TglEnable;
  glEnableClientState: TglEnableClientState;
  glEnableVertexAttribArray: TglEnableVertexAttribArray;
  glFinish: TglFinish;
  glFramebufferTexture2D: TglFramebufferTexture2D;
  glGenBuffers: TglGenBuffers;
  glGenFramebuffers: TglGenFramebuffers;
  glGenTextures: TglGenTextures;
  glGenerateMipmap: TglGenerateMipmap;
  glGetIntegerv: TglGetIntegerv;
  glGetProgramInfoLog: TglGetProgramInfoLog;
  glGetProgramiv: TglGetProgramiv;
  glGetShaderInfoLog: TglGetShaderInfoLog;
  glGetShaderiv: TglGetShaderiv;
  glGetString: TglGetString;
  glGetUniformLocation: TglGetUniformLocation;
  glHint: TglHint;
  glLinkProgram: TglLinkProgram;
  glLoadMatrixf: TglLoadMatrixf;
  glPixelStorei: TglPixelStorei;
  glReadPixels: TglReadPixels;
  glShaderSource: TglShaderSource;
  glTexCoordPointer: TglTexCoordPointer;
  glTexEnvf: TglTexEnvf;
  glTexImage2D: TglTexImage2D;
  glTexImage2DMultisample: TglTexImage2DMultisample;
  glTexParameteri: TglTexParameteri;
  glTexSubImage2D: TglTexSubImage2D;
  glUniform1i: TglUniform1i;
  glUniform1f: TglUniform1f;
  glUniform4f: TglUniform4f;
  glClearStencil: TglClearStencil;
  glStencilFunc: TglStencilFunc;
  glStencilOp: TglStencilOp;
  glStencilMask: TglStencilMask;
  glUniformMatrix3fv: TglUniformMatrix3fv;
  glUseProgram: TglUseProgram;
  glVertexAttribPointer: TglVertexAttribPointer;
  glVertexPointer: TglVertexPointer;
  glViewport: TglViewport;
  glBindFramebufferEXT: TglBindFramebufferEXT;
  glDeleteFramebuffersEXT: TglDeleteFramebuffersEXT;
  glFramebufferTexture2DEXT: TglFramebufferTexture2DEXT;
  glGenFramebuffersEXT: TglGenFramebuffersEXT;
  glGenerateMipmapEXT: TglGenerateMipmapEXT;

function InitOpenGL: Boolean;
procedure ReadExtensions;
procedure ReadImplementationProperties;

implementation

procedure imp_glActiveTexture(texture: GLenum); cdecl; external 'gl' name 'glActiveTexture';
procedure js_glActiveTexture(texture: GLenum); cdecl; begin imp_glActiveTexture(texture); end;
procedure imp_glAttachShader(programObj, shaderObj: GLhandle); cdecl; external 'gl' name 'glAttachShader';
procedure js_glAttachShader(programObj, shaderObj: GLhandle); cdecl; begin imp_glAttachShader(programObj, shaderObj); end;
procedure imp_glBindAttribLocation(programObj: GLhandle; index: GLuint; name: PGLChar); cdecl; external 'gl' name 'glBindAttribLocation';
procedure js_glBindAttribLocation(programObj: GLhandle; index: GLuint; name: PGLChar); cdecl; begin imp_glBindAttribLocation(programObj, index, name); end;
procedure imp_glBindBuffer(target: GLenum; buffer: GLuint); cdecl; external 'gl' name 'glBindBuffer';
procedure js_glBindBuffer(target: GLenum; buffer: GLuint); cdecl; begin imp_glBindBuffer(target, buffer); end;
procedure imp_glBindFramebuffer(target: GLenum; framebuffer: GLuint); cdecl; external 'gl' name 'glBindFramebuffer';
procedure js_glBindFramebuffer(target: GLenum; framebuffer: GLuint); cdecl; begin imp_glBindFramebuffer(target, framebuffer); end;
procedure imp_glBindTexture(target: GLenum; texture: GLuint); cdecl; external 'gl' name 'glBindTexture';
procedure js_glBindTexture(target: GLenum; texture: GLuint); cdecl; begin imp_glBindTexture(target, texture); end;
procedure imp_glBlendFunc(sfactor: GLenum; dfactor: GLenum); cdecl; external 'gl' name 'glBlendFunc';
procedure js_glBlendFunc(sfactor: GLenum; dfactor: GLenum); cdecl; begin imp_glBlendFunc(sfactor, dfactor); end;
procedure imp_glBlitFramebuffer(srcX0: GLint; srcY0: GLint; srcX1: GLint; srcY1: GLint; dstX0: GLint; dstY0: GLint; dstX1: GLint; dstY1: GLint; mask: GLbitfield; filter: GLenum); cdecl; external 'gl' name 'glBlitFramebuffer';
procedure js_glBlitFramebuffer(srcX0: GLint; srcY0: GLint; srcX1: GLint; srcY1: GLint; dstX0: GLint; dstY0: GLint; dstX1: GLint; dstY1: GLint; mask: GLbitfield; filter: GLenum); cdecl; begin imp_glBlitFramebuffer(srcX0, srcY0, srcX1, srcY1, dstX0, dstY0, dstX1, dstY1, mask, filter); end;
procedure imp_glBufferData(target: GLenum; size: GLsizeiptr; const data: PGLvoid; usage: GLenum); cdecl; external 'gl' name 'glBufferData';
procedure js_glBufferData(target: GLenum; size: GLsizeiptr; const data: PGLvoid; usage: GLenum); cdecl; begin imp_glBufferData(target, size, data, usage); end;
procedure imp_glBufferSubData(target: GLenum; offset: GLintptr; size: GLsizeiptr; const data: PGLvoid); cdecl; external 'gl' name 'glBufferSubData';
procedure js_glBufferSubData(target: GLenum; offset: GLintptr; size: GLsizeiptr; const data: PGLvoid); cdecl; begin imp_glBufferSubData(target, offset, size, data); end;
procedure imp_glClear(mask: GLbitfield); cdecl; external 'gl' name 'glClear';
procedure js_glClear(mask: GLbitfield); cdecl; begin imp_glClear(mask); end;
procedure imp_glClearColor(red: GLclampf; green: GLclampf; blue: GLclampf; alpha: GLclampf); cdecl; external 'gl' name 'glClearColor';
procedure js_glClearColor(red: GLclampf; green: GLclampf; blue: GLclampf; alpha: GLclampf); cdecl; begin imp_glClearColor(red, green, blue, alpha); end;
procedure imp_glColorPointer(size: GLint; _type: GLenum; stride: GLsizei; const _pointer: PGLvoid); cdecl; external 'gl' name 'glColorPointer';
procedure js_glColorPointer(size: GLint; _type: GLenum; stride: GLsizei; const _pointer: PGLvoid); cdecl; begin imp_glColorPointer(size, _type, stride, _pointer); end;
procedure imp_glCompileShader(shaderObj: GLhandle); cdecl; external 'gl' name 'glCompileShader';
procedure js_glCompileShader(shaderObj: GLhandle); cdecl; begin imp_glCompileShader(shaderObj); end;
function imp_glCreateProgram: GLhandle; cdecl; external 'gl' name 'glCreateProgram';
function js_glCreateProgram: GLhandle; cdecl; begin Result := imp_glCreateProgram; end;
function imp_glCreateShader(shaderType: GLenum): GLhandle; cdecl; external 'gl' name 'glCreateShader';
function js_glCreateShader(shaderType: GLenum): GLhandle; cdecl; begin Result := imp_glCreateShader(shaderType); end;
procedure imp_glDeleteBuffers(n: GLsizei; const buffers: PGLuint); cdecl; external 'gl' name 'glDeleteBuffers';
procedure js_glDeleteBuffers(n: GLsizei; const buffers: PGLuint); cdecl; begin imp_glDeleteBuffers(n, buffers); end;
procedure imp_glDeleteFramebuffers(n: GLsizei; const framebuffers: PGLuint); cdecl; external 'gl' name 'glDeleteFramebuffers';
procedure js_glDeleteFramebuffers(n: GLsizei; const framebuffers: PGLuint); cdecl; begin imp_glDeleteFramebuffers(n, framebuffers); end;
procedure imp_glDeleteProgram(programObj: GLhandle); cdecl; external 'gl' name 'glDeleteProgram';
procedure js_glDeleteProgram(programObj: GLhandle); cdecl; begin imp_glDeleteProgram(programObj); end;
procedure imp_glDeleteShader(shaderObj: GLhandle); cdecl; external 'gl' name 'glDeleteShader';
procedure js_glDeleteShader(shaderObj: GLhandle); cdecl; begin imp_glDeleteShader(shaderObj); end;
procedure imp_glDeleteTextures(n: GLsizei; const textures: PGLuint); cdecl; external 'gl' name 'glDeleteTextures';
procedure js_glDeleteTextures(n: GLsizei; const textures: PGLuint); cdecl; begin imp_glDeleteTextures(n, textures); end;
procedure imp_glDetachShader(programObj, shaderObj: GLhandle); cdecl; external 'gl' name 'glDetachShader';
procedure js_glDetachShader(programObj, shaderObj: GLhandle); cdecl; begin imp_glDetachShader(programObj, shaderObj); end;
procedure imp_glDisable(cap: GLenum); cdecl; external 'gl' name 'glDisable';
procedure js_glDisable(cap: GLenum); cdecl; begin imp_glDisable(cap); end;
procedure imp_glDrawArrays(mode: GLenum; first: GLint; count: GLsizei); cdecl; external 'gl' name 'glDrawArrays';
procedure js_glDrawArrays(mode: GLenum; first: GLint; count: GLsizei); cdecl; begin imp_glDrawArrays(mode, first, count); end;
procedure imp_glDrawElements(mode: GLenum; count: GLsizei; _type: GLenum; const indices: PGLvoid); cdecl; external 'gl' name 'glDrawElements';
procedure js_glDrawElements(mode: GLenum; count: GLsizei; _type: GLenum; const indices: PGLvoid); cdecl; begin imp_glDrawElements(mode, count, _type, indices); end;
procedure imp_glEnable(cap: GLenum); cdecl; external 'gl' name 'glEnable';
procedure js_glEnable(cap: GLenum); cdecl; begin imp_glEnable(cap); end;
procedure imp_glEnableClientState(_array: GLenum); cdecl; external 'gl' name 'glEnableClientState';
procedure js_glEnableClientState(_array: GLenum); cdecl; begin imp_glEnableClientState(_array); end;
procedure imp_glEnableVertexAttribArray(index: GLuint); cdecl; external 'gl' name 'glEnableVertexAttribArray';
procedure js_glEnableVertexAttribArray(index: GLuint); cdecl; begin imp_glEnableVertexAttribArray(index); end;
procedure imp_glFinish(); cdecl; external 'gl' name 'glFinish';
procedure js_glFinish(); cdecl; begin imp_glFinish(); end;
procedure imp_glFramebufferTexture2D(target: GLenum; attachment: GLenum; textarget: GLenum; texture: GLuint; level: GLint); cdecl; external 'gl' name 'glFramebufferTexture2D';
procedure js_glFramebufferTexture2D(target: GLenum; attachment: GLenum; textarget: GLenum; texture: GLuint; level: GLint); cdecl; begin imp_glFramebufferTexture2D(target, attachment, textarget, texture, level); end;
procedure imp_glGenBuffers(n: GLsizei; buffers: PGLuint); cdecl; external 'gl' name 'glGenBuffers';
procedure js_glGenBuffers(n: GLsizei; buffers: PGLuint); cdecl; begin imp_glGenBuffers(n, buffers); end;
procedure imp_glGenFramebuffers(n: GLsizei; framebuffers: PGLuint); cdecl; external 'gl' name 'glGenFramebuffers';
procedure js_glGenFramebuffers(n: GLsizei; framebuffers: PGLuint); cdecl; begin imp_glGenFramebuffers(n, framebuffers); end;
procedure imp_glGenTextures(n: GLsizei; textures: PGLuint); cdecl; external 'gl' name 'glGenTextures';
procedure js_glGenTextures(n: GLsizei; textures: PGLuint); cdecl; begin imp_glGenTextures(n, textures); end;
procedure imp_glGenerateMipmap(target: GLenum); cdecl; external 'gl' name 'glGenerateMipmap';
procedure js_glGenerateMipmap(target: GLenum); cdecl; begin imp_glGenerateMipmap(target); end;
procedure imp_glGetIntegerv(pname: GLenum; params: PGLint); cdecl; external 'gl' name 'glGetIntegerv';
procedure js_glGetIntegerv(pname: GLenum; params: PGLint); cdecl; begin imp_glGetIntegerv(pname, params); end;
procedure imp_glGetProgramInfoLog(programObj: GLHandle; maxLength: glsizei; length: PGLSizei; infoLog: PGLChar); cdecl; external 'gl' name 'glGetProgramInfoLog';
procedure js_glGetProgramInfoLog(programObj: GLHandle; maxLength: glsizei; length: PGLSizei; infoLog: PGLChar); cdecl; begin imp_glGetProgramInfoLog(programObj, maxLength, length, infoLog); end;
procedure imp_glGetProgramiv(programObj: GLhandle; pname: GLenum; params: PGLInt); cdecl; external 'gl' name 'glGetProgramiv';
procedure js_glGetProgramiv(programObj: GLhandle; pname: GLenum; params: PGLInt); cdecl; begin imp_glGetProgramiv(programObj, pname, params); end;
procedure imp_glGetShaderInfoLog(shaderObj: GLHandle; maxLength: glsizei; length: PGLSizei; infoLog: PGLChar); cdecl; external 'gl' name 'glGetShaderInfoLog';
procedure js_glGetShaderInfoLog(shaderObj: GLHandle; maxLength: glsizei; length: PGLSizei; infoLog: PGLChar); cdecl; begin imp_glGetShaderInfoLog(shaderObj, maxLength, length, infoLog); end;
procedure imp_glGetShaderiv(shaderObj: GLhandle; pname: GLenum; params: PGLInt); cdecl; external 'gl' name 'glGetShaderiv';
procedure js_glGetShaderiv(shaderObj: GLhandle; pname: GLenum; params: PGLInt); cdecl; begin imp_glGetShaderiv(shaderObj, pname, params); end;
function imp_glGetString(name: GLenum): PAnsiChar; cdecl; external 'gl' name 'glGetString';
function js_glGetString(name: GLenum): PAnsiChar; cdecl; begin Result := imp_glGetString(name); end;
function imp_glGetUniformLocation(programObj: GLhandle; const char: PGLChar): glint; cdecl; external 'gl' name 'glGetUniformLocation';
function js_glGetUniformLocation(programObj: GLhandle; const char: PGLChar): glint; cdecl; begin Result := imp_glGetUniformLocation(programObj, char); end;
procedure imp_glHint(target: GLenum; mode: GLenum); cdecl; external 'gl' name 'glHint';
procedure js_glHint(target: GLenum; mode: GLenum); cdecl; begin imp_glHint(target, mode); end;
procedure imp_glLinkProgram(programObj: GLHandle); cdecl; external 'gl' name 'glLinkProgram';
procedure js_glLinkProgram(programObj: GLHandle); cdecl; begin imp_glLinkProgram(programObj); end;
procedure imp_glLoadMatrixf(const m: PGLfloat); cdecl; external 'gl' name 'glLoadMatrixf';
procedure js_glLoadMatrixf(const m: PGLfloat); cdecl; begin imp_glLoadMatrixf(m); end;
procedure imp_glPixelStorei(pname: GLenum; param: GLint); cdecl; external 'gl' name 'glPixelStorei';
procedure js_glPixelStorei(pname: GLenum; param: GLint); cdecl; begin imp_glPixelStorei(pname, param); end;
procedure imp_glReadPixels(x: GLint; y: GLint; width: GLsizei; height: GLsizei; format: GLenum; _type: GLenum; pixels: PGLvoid); cdecl; external 'gl' name 'glReadPixels';
procedure js_glReadPixels(x: GLint; y: GLint; width: GLsizei; height: GLsizei; format: GLenum; _type: GLenum; pixels: PGLvoid); cdecl; begin imp_glReadPixels(x, y, width, height, format, _type, pixels); end;
procedure imp_glShaderSource(shaderObj: GLHandle; count: glsizei; const _string: PPGLChar; lengths: pglint); cdecl; external 'gl' name 'glShaderSource';
procedure js_glShaderSource(shaderObj: GLHandle; count: glsizei; const _string: PPGLChar; lengths: pglint); cdecl; begin imp_glShaderSource(shaderObj, count, _string, lengths); end;
procedure imp_glTexCoordPointer(size: GLint; _type: GLenum; stride: GLsizei; const _pointer: PGLvoid); cdecl; external 'gl' name 'glTexCoordPointer';
procedure js_glTexCoordPointer(size: GLint; _type: GLenum; stride: GLsizei; const _pointer: PGLvoid); cdecl; begin imp_glTexCoordPointer(size, _type, stride, _pointer); end;
procedure imp_glTexEnvf(target: GLenum; pname: GLenum; param: GLfloat); cdecl; external 'gl' name 'glTexEnvf';
procedure js_glTexEnvf(target: GLenum; pname: GLenum; param: GLfloat); cdecl; begin imp_glTexEnvf(target, pname, param); end;
procedure imp_glTexImage2D(target: GLenum; level: GLint; internalformat: GLint; width: GLsizei; height: GLsizei; border: GLint; format: GLenum; _type: GLenum; const pixels: PGLvoid); cdecl; external 'gl' name 'glTexImage2D';
procedure js_glTexImage2D(target: GLenum; level: GLint; internalformat: GLint; width: GLsizei; height: GLsizei; border: GLint; format: GLenum; _type: GLenum; const pixels: PGLvoid); cdecl; begin imp_glTexImage2D(target, level, internalformat, width, height, border, format, _type, pixels); end;
procedure imp_glTexImage2DMultisample(target: GLenum; samples: GLsizei; internalformat: GLint; width: GLsizei; height: GLsizei; fixedsamplelocations: GLboolean); cdecl; external 'gl' name 'glTexImage2DMultisample';
procedure js_glTexImage2DMultisample(target: GLenum; samples: GLsizei; internalformat: GLint; width: GLsizei; height: GLsizei; fixedsamplelocations: GLboolean); cdecl; begin imp_glTexImage2DMultisample(target, samples, internalformat, width, height, fixedsamplelocations); end;
procedure imp_glTexParameteri(target: GLenum; pname: GLenum; param: GLint); cdecl; external 'gl' name 'glTexParameteri';
procedure js_glTexParameteri(target: GLenum; pname: GLenum; param: GLint); cdecl; begin imp_glTexParameteri(target, pname, param); end;
procedure imp_glTexSubImage2D(target: GLenum; level: GLint; xoffset: GLint; yoffset: GLint; width: GLsizei; height: GLsizei; format: GLenum; _type: GLenum; const pixels: PGLvoid); cdecl; external 'gl' name 'glTexSubImage2D';
procedure js_glTexSubImage2D(target: GLenum; level: GLint; xoffset: GLint; yoffset: GLint; width: GLsizei; height: GLsizei; format: GLenum; _type: GLenum; const pixels: PGLvoid); cdecl; begin imp_glTexSubImage2D(target, level, xoffset, yoffset, width, height, format, _type, pixels); end;
procedure imp_glUniform1i(location: GLint; v0: GLint); cdecl; external 'gl' name 'glUniform1i';
procedure js_glUniform1i(location: GLint; v0: GLint); cdecl; begin imp_glUniform1i(location, v0); end;
procedure imp_glUniform1f(location: GLint; v0: GLfloat); cdecl; external 'gl' name 'glUniform1f';
procedure js_glUniform1f(location: GLint; v0: GLfloat); cdecl; begin imp_glUniform1f(location, v0); end;
procedure imp_glUniform4f(location: GLint; v0, v1, v2, v3: GLfloat); cdecl; external 'gl' name 'glUniform4f';
procedure js_glUniform4f(location: GLint; v0, v1, v2, v3: GLfloat); cdecl; begin imp_glUniform4f(location, v0, v1, v2, v3); end;
procedure imp_glClearStencil(s: GLint); cdecl; external 'gl' name 'glClearStencil';
procedure js_glClearStencil(s: GLint); cdecl; begin imp_glClearStencil(s); end;
procedure imp_glStencilFunc(func: GLenum; ref: GLint; mask: GLuint); cdecl; external 'gl' name 'glStencilFunc';
procedure js_glStencilFunc(func: GLenum; ref: GLint; mask: GLuint); cdecl; begin imp_glStencilFunc(func, ref, mask); end;
procedure imp_glStencilOp(fail, zfail, zpass: GLenum); cdecl; external 'gl' name 'glStencilOp';
procedure js_glStencilOp(fail, zfail, zpass: GLenum); cdecl; begin imp_glStencilOp(fail, zfail, zpass); end;
procedure imp_glStencilMask(mask: GLuint); cdecl; external 'gl' name 'glStencilMask';
procedure js_glStencilMask(mask: GLuint); cdecl; begin imp_glStencilMask(mask); end;
procedure imp_glUniformMatrix3fv(location: GLint; count: GLsizei; transpose: GLboolean; value: PGLfloat); cdecl; external 'gl' name 'glUniformMatrix3fv';
procedure js_glUniformMatrix3fv(location: GLint; count: GLsizei; transpose: GLboolean; value: PGLfloat); cdecl; begin imp_glUniformMatrix3fv(location, count, transpose, value); end;
procedure imp_glUseProgram(programObj: GLhandle); cdecl; external 'gl' name 'glUseProgram';
procedure js_glUseProgram(programObj: GLhandle); cdecl; begin imp_glUseProgram(programObj); end;
procedure imp_glVertexAttribPointer(index: GLuint; size: GLint; _type: GLenum; normalized: GLboolean; stride: GLsizei; const _pointer: PGLvoid); cdecl; external 'gl' name 'glVertexAttribPointer';
procedure js_glVertexAttribPointer(index: GLuint; size: GLint; _type: GLenum; normalized: GLboolean; stride: GLsizei; const _pointer: PGLvoid); cdecl; begin imp_glVertexAttribPointer(index, size, _type, normalized, stride, _pointer); end;
procedure imp_glVertexPointer(size: GLint; _type: GLenum; stride: GLsizei; const _pointer: PGLvoid); cdecl; external 'gl' name 'glVertexPointer';
procedure js_glVertexPointer(size: GLint; _type: GLenum; stride: GLsizei; const _pointer: PGLvoid); cdecl; begin imp_glVertexPointer(size, _type, stride, _pointer); end;
procedure imp_glViewport(x: GLint; y: GLint; width: GLsizei; height: GLsizei); cdecl; external 'gl' name 'glViewport';
procedure js_glViewport(x: GLint; y: GLint; width: GLsizei; height: GLsizei); cdecl; begin imp_glViewport(x, y, width, height); end;

function InitOpenGL: Boolean;
begin
  glActiveTexture := @js_glActiveTexture;
  glAttachShader := @js_glAttachShader;
  glBindAttribLocation := @js_glBindAttribLocation;
  glBindBuffer := @js_glBindBuffer;
  glBindFramebuffer := @js_glBindFramebuffer;
  glBindTexture := @js_glBindTexture;
  glBlendFunc := @js_glBlendFunc;
  glBlitFramebuffer := @js_glBlitFramebuffer;
  glBufferData := @js_glBufferData;
  glBufferSubData := @js_glBufferSubData;
  glClear := @js_glClear;
  glClearColor := @js_glClearColor;
  glColorPointer := @js_glColorPointer;
  glCompileShader := @js_glCompileShader;
  glCreateProgram := @js_glCreateProgram;
  glCreateShader := @js_glCreateShader;
  glDeleteBuffers := @js_glDeleteBuffers;
  glDeleteFramebuffers := @js_glDeleteFramebuffers;
  glDeleteProgram := @js_glDeleteProgram;
  glDeleteShader := @js_glDeleteShader;
  glDeleteTextures := @js_glDeleteTextures;
  glDetachShader := @js_glDetachShader;
  glDisable := @js_glDisable;
  glDrawArrays := @js_glDrawArrays;
  glDrawElements := @js_glDrawElements;
  glEnable := @js_glEnable;
  glEnableClientState := @js_glEnableClientState;
  glEnableVertexAttribArray := @js_glEnableVertexAttribArray;
  glFinish := @js_glFinish;
  glFramebufferTexture2D := @js_glFramebufferTexture2D;
  glGenBuffers := @js_glGenBuffers;
  glGenFramebuffers := @js_glGenFramebuffers;
  glGenTextures := @js_glGenTextures;
  glGenerateMipmap := @js_glGenerateMipmap;
  glGetIntegerv := @js_glGetIntegerv;
  glGetProgramInfoLog := @js_glGetProgramInfoLog;
  glGetProgramiv := @js_glGetProgramiv;
  glGetShaderInfoLog := @js_glGetShaderInfoLog;
  glGetShaderiv := @js_glGetShaderiv;
  glGetString := @js_glGetString;
  glGetUniformLocation := @js_glGetUniformLocation;
  glHint := @js_glHint;
  glLinkProgram := @js_glLinkProgram;
  glLoadMatrixf := @js_glLoadMatrixf;
  glPixelStorei := @js_glPixelStorei;
  glReadPixels := @js_glReadPixels;
  glShaderSource := @js_glShaderSource;
  glTexCoordPointer := @js_glTexCoordPointer;
  glTexEnvf := @js_glTexEnvf;
  glTexImage2D := @js_glTexImage2D;
  glTexImage2DMultisample := @js_glTexImage2DMultisample;
  glTexParameteri := @js_glTexParameteri;
  glTexSubImage2D := @js_glTexSubImage2D;
  glUniform1i := @js_glUniform1i;
  glUniform1f := @js_glUniform1f;
  glUniform4f := @js_glUniform4f;
  glClearStencil := @js_glClearStencil;
  glStencilFunc := @js_glStencilFunc;
  glStencilOp := @js_glStencilOp;
  glStencilMask := @js_glStencilMask;
  glUniformMatrix3fv := @js_glUniformMatrix3fv;
  glUseProgram := @js_glUseProgram;
  glVertexAttribPointer := @js_glVertexAttribPointer;
  glVertexPointer := @js_glVertexPointer;
  glViewport := @js_glViewport;
  Result := True;
end;

procedure ReadExtensions;
begin
end;

procedure ReadImplementationProperties;
begin
end;

end.
