#!/usr/bin/env python3
"""Generates web/js/gostek-data.js (the soldier preview of the menu) from the game's own
tables: the body part list of src/client/GostekGraphics.inc and the texture list of
src/shared/gfx.inc. Run it again when either file changes."""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INC = os.path.join(ROOT, 'src/client/GostekGraphics.inc')
GFX = os.path.join(ROOT, 'src/shared/gfx.inc')
OUT = os.path.join(ROOT, 'web/js/gostek-data.js')

COLORS = {'COLOR_NONE': 0, 'COLOR_MAIN': 1, 'COLOR_PANTS': 2, 'COLOR_SKIN': 3,
          'COLOR_HAIR': 4, 'COLOR_CYGAR': 5, 'COLOR_HEADBLOOD': 6}
ALPHAS = {'ALPHA_BASE': 0, 'ALPHA_BLOOD': 1, 'ALPHA_NADES': 2}

gfx_text = open(GFX).read()
gfx_ids = {name: int(v) for name, v in re.findall(r'\bGFX_(\w+)\s*=\s*(\d+);', gfx_text)}
paths = {gfx_ids[name]: path for name, path in
         re.findall(r"\(ID: GFX_(\w+); Group: \w+; Path: '([^']+)'", gfx_text)}

part_re = re.compile(
    r"GOSTEK_(\w+)\s*=\s*(\d+);\{\$ELSE\}Def\('(\w+)',\s*(\w+),\s*(\d+),\s*(\d+),\s*"
    r"([-\d.]+),\s*([-\d.]+),\s*(\d),\s*(\d),\s*(\d),\s*([-\d.]+),\s*(\w+),\s*(\w+)\s*\)")
parts = []
for m in part_re.finditer(open(INC).read()):
    const, index, ident, image, p1, p2, cx, cy, vis, flip, team, flex, color, alpha = m.groups()
    assert int(index) == len(parts), ident
    parts.append(dict(const=const, id=ident, image=0 if image == '0' else gfx_ids[image[4:]],
                      p1=int(p1), p2=int(p2), cx=float(cx), cy=float(cy), visible=vis == '1',
                      flip=flip == '1', team=team == '1', flex=float(flex),
                      color=COLORS[color], alpha=ALPHAS[alpha]))
assert len(parts) == 131, len(parts)

team2 = gfx_ids['GOSTEK_TEAM2_STOPA'] - gfx_ids['GOSTEK_STOPA']
# jet flames (Sparks.pas style 62)
sparks = {'JETFIRE': gfx_ids['SPARKS_JETFIRE']}
used = set(sparks.values())
for p in parts:
    if p['image']:
        for t in (0, team2 if p['team'] else 0):
            used.update({p['image'] + t, p['image'] + t + (1 if p['flip'] else 0)})


def num(v):
    return ('%g' % v)


lines = [
    '// Generated by tools/gen-gostek-data.py from src/client/GostekGraphics.inc and',
    '// src/shared/gfx.inc: the soldier\'s body parts as the game draws them. Do not edit.',
    '',
    '// texture id -> file in the game data (the game also accepts .png for .bmp names)',
    'export const TEXTURES = {',
]
lines += [f"  {i}: '{paths[i]}'," for i in sorted(used)]
lines += ['};', '', f'export const TEAM2_OFFSET = {team2};', '',
          'export const SPARKS = { ' + ', '.join(f'{k}: {v}' for k, v in sparks.items()) + ' };', '',
          '// [name, texture, p1, p2, centerX, centerY, visible, flip, team, flex, color, alpha]',
          'export const PARTS = [']
for p in parts:
    lines.append(f"  ['{p['id']}', {p['image']}, {p['p1']}, {p['p2']}, {num(p['cx'])}, {num(p['cy'])}, "
                 f"{int(p['visible'])}, {int(p['flip'])}, {int(p['team'])}, {num(p['flex'])}, "
                 f"{p['color']}, {p['alpha']}],")
lines += ['];', '', '// part index by GOSTEK_ constant name', 'export const PART = {']
lines += [f"  {p['const']}: {i}," for i, p in enumerate(parts)]
lines += ['};', '']
open(OUT, 'w').write('\n'.join(lines))
print(f'wrote {os.path.relpath(OUT, ROOT)}: {len(parts)} parts, {len(used)} textures')
